title: Weihong Sheng
logo: /assets/img/photo.png
description: Two roads diverged in a yellow wood, and sorry I could not travel both
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

contact:
  scholar: "https://scholar.google.com/citations?user=G2b2wuIAAAAJ&hl=en"
  github: "https://github.com/swh256"
  email: "shengwe [at] iu.edu"
  location: "3051L Luddy Hall, Bloomington, IN 47408"

github:
      is_project_page: false
      another_url: another value
